require("packs/admins/jquery-3.5.1.min")
require("jquery")
require("popper.js")
require("turbolinks")
require("bootstrap")
require("packs/admins/bootstrap.bundle.min")
require("cocoon")
require("packs/admins/scripts")
